### ISSUE TITLE
Not able to get score

### ISSUE THREAD

**Issue by techdsg** [andrewda/hltv-scorebot#10]
Hi,

I am trying to get score->currentMap / mapScores data, but without any success. I am using 

```
sb.on('score', function(data) {
    console.log('currentCtScore:', data.mapScores.currentCtScore);
});
```

Any ideas? thanks in advance.

**Comment by andrewda** [comment]
Could you print out your `data` object? HLTV may have changed up their responses, in which case I'll update the README with the appropriate responses.

**Comment by techdsg** [comment]
I can print other elements like roundEnd, kill, roundStart, but no idea about score.

**Comment by andrewda** [comment]
If you just print the `data` object, though, what shows up?

**Comment by techdsg** [comment]
I tried 

`sb.on('score', function(data) {
    console.log('data:', data);

});`

but nothing. when is the score triggered?

**Comment by andrewda** [comment]
It should be triggered after every round end. I'll see if HLTV changed anything.

**Comment by techdsg** [comment]
Thanks, would be very helpful.

**Comment by andrewda** [comment]
It seems that the `score` event is not used anymore, and now `scoreboard` is emitted solely. I will probably remove the `score` event as I want this to be a wrapper for HLTV, so I would suggest using the `scoreboard` event. I will also add a `getScore()` method so that the score can be easily retrieved.

**Comment by colealanroberts** [comment]
Any update on this?

**Comment by andrewda** [comment]
@colealanroberts I actually just finished testing it out today - will push the code.
